#!/usr/bin/env bun
/**
 * gen-dkbb-catalog — registry JSON → generated TS for the dkbb-catalog plugin.
 * Run: bun scripts/gen-dkbb-catalog.ts
 * Source: ~/stacks/v24-library/registry/{archetypes,board-profiles}.json
 * Output: packages/dkbb-catalog/src/generated/{archetypes,profiles}.ts
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'

const REGISTRY = process.env.DKBB_REGISTRY ?? '/home/kkadmin/stacks/v24-library/registry'
const OUT = new URL('../packages/dkbb-catalog/src/generated/', import.meta.url).pathname

type ParamSpec = { default: number; min: number; max: number; step: number }
type Archetype = {
  id: string
  label: string
  category: string
  runTier: 'base' | 'wall' | 'tall'
  params: { width: ParamSpec; depth: ParamSpec; height: ParamSpec }
  partsCount: number
  profileCount: number
}
type Profile = {
  id: string
  label: string
  board: { core: string; emission: string; thicknessMm: number }
  frontSystem: string
  materials: { carcass: string | null; front: string | null; plinth: string | null }
}

const archetypes: Archetype[] = JSON.parse(readFileSync(`${REGISTRY}/archetypes.json`, 'utf8'))
const profiles: Profile[] = JSON.parse(readFileSync(`${REGISTRY}/board-profiles.json`, 'utf8'))

// Drop archetypes with unusable defaults (zero/negative dims from stray bboxes).
const usable = archetypes
  .filter(
    (a) => a.params.width.default > 0 && a.params.depth.default > 0 && a.params.height.default > 0,
  )
  .map(({ id, label, category, runTier, params, partsCount, profileCount }) => ({
    id,
    label,
    category,
    runTier,
    params,
    partsCount,
    profileCount,
  }))

const header = `// AUTO-GENERATED by scripts/gen-dkbb-catalog.ts — do not edit by hand.
// Source: V24-Library registry (${usable.length}/${archetypes.length} archetypes usable, ${profiles.length} profiles).
`

const archTs = `${header}
export type DkbbArchetype = {
  id: string
  label: string
  category: string
  runTier: 'base' | 'wall' | 'tall'
  params: { width: ParamSpec; depth: ParamSpec; height: ParamSpec }
  partsCount: number
  profileCount: number
}
export type ParamSpec = { default: number; min: number; max: number; step: number }

export const ARCHETYPES: DkbbArchetype[] = ${JSON.stringify(usable, null, 1)} as DkbbArchetype[]

export const ARCHETYPE_IDS = ARCHETYPES.map((a) => a.id) as [string, ...string[]]
export const CATEGORIES = [...new Set(ARCHETYPES.map((a) => a.category))] as [string, ...string[]]
`

const profTs = `${header}
export type DkbbProfile = {
  id: string
  label: string
  board: { core: string; emission: string; thicknessMm: number }
  frontSystem: string
  materials: { carcass: string | null; front: string | null; plinth: string | null }
}

export const PROFILES: DkbbProfile[] = ${JSON.stringify(
  profiles.map(({ id, label, board, frontSystem, materials }) => ({
    id,
    label,
    board,
    frontSystem,
    materials,
  })),
  null,
  1,
)}

export const PROFILE_IDS = PROFILES.map((p) => p.id) as [string, ...string[]]
`

mkdirSync(OUT, { recursive: true })
writeFileSync(`${OUT}/archetypes.ts`, archTs)
writeFileSync(`${OUT}/profiles.ts`, profTs)
console.log(`archetypes: ${usable.length}/${archetypes.length}, profiles: ${profiles.length} -> ${OUT}`)
